on:
  workflow_dispatch:
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@main
      with:
        envkey_SECRETS: ${{ toJSON(secrets) }}
        file_name: .github_secrets
        fail_on_empty: false
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github_secrets
        path: .github_secrets
